# Generated by Django 5.0.7 on 2024-07-22 21:17

import cloudinary.models
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Imagen')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destacar')),
            ],
            options={
                'verbose_name': 'Foto Publicitaria',
                'verbose_name_plural': 'Fotos Publicitarias',
            },
        ),
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, validators=[marketing.models.file_validation], verbose_name='Video')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Video Promocional',
                'verbose_name_plural': 'Videos Promocionales',
            },
        ),
    ]
